# Data directories
DICO_SNDS_PATH = 'data/dico-snds'
APP_DICO_SNDS_PATH = 'data/app_dico-snds'
DCIRS_SCHMEMA_DIR = 'data/tableschema/DCIRS'
DCIR_SCHMEMA_DIR = 'data/tableschema/DCIR'
DCIR_DCIRS_SCHEMA_DIR = 'data/tableschema/DCIR_DCIRS'
BENEFICIARY_SCHEMA_DIR = 'data/tableschema/BENEFICIAIRE'
DECES_SCHEMA_DIR = 'data/tableschema/Causes de décès'
CARTO_PATHO_SCHEMA_DIR = 'data/tableschema/CARTOGRAPHIE_PATHOLOGIES'
PMSI_MCO_SCHEMA_DIR = 'data/tableschema/PMSI MCO'
PMSI_HAD_SCHEMA_DIR = 'data/tableschema/PMSI HAD'
PMSI_RIMP_SCHEMA_DIR = 'data/tableschema/PMSI RIM-P'
PMSI_SSR_SCHEMA_DIR = 'data/tableschema/PMSI SSR'
MAIN_SCHEMA_DIR = 'data/tableschema'

# Data files
TABLES_SIDEBAR_JS_PATH = 'data/tables_sidebar.js'

# https://frictionlessdata.io/specs/table-schema/#types-and-formats

STRING = 'string'
NUMBER = 'number'
INTEGER = 'integer'
BOOLEAN = 'boolean'
OBJECT = 'object'
ARRAY = 'array'
DATE = 'date'
TIME = 'time'
DATETIME = 'datetime'
YEAR = 'year'
YEARMONTH = 'yearmonth'
DURATION = 'duration'
GEOPOINT = 'geopoint'
GEOJSON = 'geojson'
ANY = 'any'
