# Data directories
DICO_SNDS_PATH = 'data/dico-snds'
DCIRS_SCHMEMA_DIR = 'data/tableschema/DCIRS'
DCIR_SCHMEMA_DIR = 'data/tableschema/DCIR'
DCIR_DCIRS_SCHEMA_DIR = 'data/tableschema/DCIR_DCIRS'
BENEFICIARY_SCHEMA_DIR = 'data/tableschema/BENEFICIAIRE'
MAIN_SCHEMA_DIR = 'data/tableschema'

# https://frictionlessdata.io/specs/table-schema/#types-and-formats

STRING = 'string'
NUMBER = 'number'
INTEGER = 'integer'
BOOLEAN = 'boolean'
OBJECT = 'object'
ARRAY = 'array'
DATE = 'date'
TIME = 'time'
DATETIME = 'datetime'
YEAR = 'year'
YEARMONTH = 'yearmonth'
DURATION = 'duration'
GEOPOINT = 'geopoint'
GEOJSON = 'geojson'
ANY = 'any'
